### ISSUE TITLE
Suggest the card type within the card number prefix data.

### ISSUE THREAD

**Issue by hotoo** [ramoona/banks-db#104]
I have a China Merchants Bank - Dual-Currency Credit Card, prefix is `5187 10`,  the card type is UnionPay AND MasterCard.

I find the code, types rule is write in type.js, and one card number just have one type.

So, I suggest the card type write in the card number prefix data, like:

banks/%country%/bankName.json

``` json
{
  ...,
  "prefixes": {
    "518710": {
      "types": ["UnionPay", "MasterCard"]
    },
    "622609": {
      "types": "UnionPay"
    }
  }
}
```
## Credit Card, Savings Deposit Card, Prepaid card ...

How about to detect this?

Usually, One card is the one category of Credit Card(CC), Savings Deposit Card(DC), Prepaid Card(PC), Semi Credit Card(SCC)

**Comment by ai** [comment]
We already detects bank card in `type.js` (we don't need database for `visa`/`mastercard` detection, they have different first number)

**Comment by ramoona** [comment]
@hotoo according to www.bindb.com your card's type is MasterCard

**Comment by hotoo** [comment]
Yes, it's UnionPay **AND** MasterCard.

**Comment by hotoo** [comment]
In China, one bank card with two type is very usual.

![](http://assets.91zhiwang.com/baike/wp-content/uploads/2015/12/0002.png)
![](http://www.mobabo.com/uploads/2_4184609862x1865336484_21.jpg)
![](http://p3.so.qhimg.com/t016ca9bf77c4c22be8.jpg)
![](http://www.meng800.com/article/uploadfile/2014/0731/20140731083507590.jpg)
![](http://p7.qhimg.com/t01823d7e476b8698f5.jpg)
![](http://i3.cqnews.net/news/attachement/jpg/site82/2011-05-20/6551224428159844431.jpg)

**Comment by ai** [comment]
@hotoo strange. Thanks for info. Do you have any information how it works?

**Comment by hotoo** [comment]
As I know, it's China UnionPay cooperation with MasterCard or VISA.

In China, most of bank card must be type of UnionPay, but many people need MasterCard or VISA card. usually, this situation is happen to a Credit Card.

I will be read more infomation for this.

**Comment by ai** [comment]
@hotoo as I know bank card could have only one card number. Union Pay cards start from `62` or `88`. Maybe this card numbers is only MasterCard, but Union Pay different number is encoded to chip?

**Comment by ramoona** [comment]
It looks like we can't detect this case. And about `Credit Card, Savings Deposit Card, Prepaid card` - I don't think it can be used in UI so there is no need to have it in bank data. Thanks for proposal.
