### ISSUE TITLE
'Forked processes must have an IPC channel'

### ISSUE THREAD

**Issue by Javid-Izadfar** [ramoona/banks-db#108]
I'm getting 'Forked processes must have an IPC channel' (before making any changes) which make test fail. any idea what's this about?

**Comment by ramoona** [comment]
this probably caused by old [AVA](https://github.com/avajs/ava) version :-(
stay tuned for next release :)

**Comment by Javid-Izadfar** [comment]
Uh Okay. I'll be adding Iranian banks any way. wish AVA be ready in time.

**Comment by ramoona** [comment]
thanks for contributing :-)
