### ISSUE TITLE
Get BINs from BinList

### ISSUE THREAD

**Issue by VersatilityWerks** [ramoona/banks-db#112]
This is a pretty complete list. It doesn't have brand colors or anything, but you can probably start with this and add that stuff on. It'll help complete your JSON files better.

https://github.com/binlist/data/blob/master/ranges.csv

**Comment by VersatilityWerks** [comment]
Nevermind mine. I see you already got this suggestion.
https://github.com/ramoona/banks-db/issues/63

**Comment by ramoona** [comment]
yep, but thank you anyway :)

**Comment by VersatilityWerks** [comment]
NP :)
