### ISSUE TITLE
Separate banks file by countries

### ISSUE THREAD

**Issue by altmind** [ramoona/banks-db#12]
There are many banks that work internationally, we need to have one bank-json for bank operating in each country.

For example, there are Sberbank in CZ in BY and in RU. There is VTB in RU and BY. There are Alfabank in RU and BY.

I suggest that we create directory for each country in banks folder and put ambigous jsons here.
Non-ambigous jsons may be left where they are. We also need to adjust build scripts?

What do you think? Will PR with those changes be welcome?

**Comment by ai** [comment]
Looks good. At least every bank can work only in one country, as I know.

**Comment by ai** [comment]
Also mayb you should wait @Ramoona decision. I am here only as Éminence grise.

**Comment by ramoona** [comment]
done in [0.7.0](https://github.com/ramoona/banks-db/releases/tag/0.7.0) release :)
