### ISSUE TITLE
Add N26 bank

### ISSUE THREAD

**Issue by stevehansen** [ramoona/banks-db#120]
Prefix 535584 (for me, image shows another one)

https://n26.com/eu/mastercard/

![preview](https://n26.com/content/uploads/2016/11/n26-mastercard.png)

**Comment by ramoona** [comment]
thanks! will add in next release)

**Comment by csachs** [comment]
Hi, another N26 user here:
My card's prefix is:
53558**5**

**Comment by fnnzzz** [comment]
done, 
pr - #136
