### ISSUE TITLE
Add flag to distinguish Closed/Defunt banks

### ISSUE THREAD

**Issue by altmind** [Ramoona/banks-db#14]
There are examples of banks that no longer issue cards to customers and banks with revoked licenses. I suggest adding some flag to json to mark those banks, for example "defunct: true"

**Comment by ai** [comment]
How we can use it in billing form?

**Comment by altmind** [comment]
We can show the user the card wont go throught

**Comment by ai** [comment]
Yeap, mybe it wil be useful. I think we can think about on first revoked bank from this DB.

**Comment by altmind** [comment]
I'm going to push PR with all BY banks and there is already a bank with revoked license there, Is it fine if i mark it with "defunct" ?

**Comment by Ramoona** [comment]
I guess we can add "defunct" like an optional property

**Comment by Ramoona** [comment]
added "defunct" property to schema d80bba72abfde799d8b1ba9ed59bb8266773cc36 and contribution guide da87987837135292aa2e8c48dfc9ce116a88db47
