### ISSUE TITLE
full database from binlist/data/

### ISSUE THREAD

**Issue by iamstarkov** [ramoona/banks-db#148]
there is a microservice https://binlist.net/
and it has database stored on github https://github.com/binlist/data/blob/master/ranges.csv

perhaps, you can take it

**Comment by iamstarkov** [comment]
and that database is very very detailed

**Comment by ramoona** [comment]
we already discussed that in #63 :) we can parse this data but still have to add brand colors manually :( although simple bank detection without any color is better then no detection at all) the thing is after including binlist data in Banks DB our final bundle will be kinda huge – some GZip required. maybe store in CDN would be a good idea

**Comment by iamstarkov** [comment]
unpkg is cdn and do gzip by default

**Comment by iamstarkov** [comment]
https://unpkg.com/banks-db@0.11.0
