### ISSUE TITLE
Consider removing manual require of each individual banks/*.json

### ISSUE THREAD

**Issue by altmind** [ramoona/banks-db#15]
See index.js:
```
const banks = [
  require('./banks/alfabank'),
  require('./banks/raiffeisen'),
  require('./banks/sberbank'),
  require('./banks/tinkoff'),
  require('./banks/vtb24'),
  require('./banks/mdm'),
];
```
Those requires bloats the main file(and it will grow in future) and create unnecessary step when adding new banks. We can either move those requires to banks/index.js (1) or just import everything from /banks directory while iterating over its files(2). Either way will make at first lint test unnecessary(YAY).

**Comment by ai** [comment]
Do you have any solution, that will works for Browserify and webpack too?

**Comment by altmind** [comment]
yes, it will. webpack will require specific loader, as always.

**Comment by ai** [comment]
Special loader is not a useful way.

**Comment by altmind** [comment]
maybe lets build webpack harness to build `dist` version of this lib?

i cannot tell exactly, will it work with webpack out of the box - i need some playground to test. i cannot tell if current setup work with webpack as well. webpack is huge and have bazillion of options.

**Comment by altmind** [comment]
building dist version is also very likely to be a precondition to publishing to cdnjs, so we may need to do that anyway.

**Comment by altmind** [comment]
by the way, do we need webpack AND browserify. or webpack OR browserify? i guess users wont care wich tool their dist package was built with?

**Comment by ai** [comment]
This solutions looks too complicated. Linter just works. Without separated build and any magic.

**Comment by altmind** [comment]
can we go with (1) option then? its not complex. Basically we just create index.js that requires files in current directory and all (necessary) direcrories in current dir. index.js for the files all the way down the dir tree.

require('./banks')
banks/index.js:
exports = [require('./citibank'), require('./ru'), require('./by')]
banks/ru/index.js:
exports = [require('./alphabank')]

**Comment by ai** [comment]
Yeap, having a `index.js` in every country dir looks good.

**Comment by ramoona** [comment]
done in [0.7.0](https://github.com/ramoona/banks-db/releases/tag/0.7.0) release :)
