### ISSUE TITLE
Add Bidvest Bank

### ISSUE THREAD

**Issue by WilhelmErasmus** [ramoona/banks-db#158]
425668
South Africa
https://www.bidvestbank.co.za/

**Comment by WilhelmErasmus** [comment]
This card still is not supported in the demo @ramoona

**Comment by ramoona** [comment]
@WilhelmErasmus sorry but demo is outdated now 😅 I will update it soon

**Comment by WilhelmErasmus** [comment]
@ramoona cool. Sorry for spamming with notifications.

**Comment by ramoona** [comment]
@WilhelmErasmus all good, thanks for participation)
