### ISSUE TITLE
How to use banks-db

### ISSUE THREAD

**Issue by shkupjane** [ramoona/banks-db#162]
hi,
how can i add this plugin into my asp.net project? can u help me pls?

**Comment by shkupjane** [comment]
thanks, which bin api u suggest? i want use it with js in my asp.net project.

**Comment by shkupjane** [comment]
thanks, which bin api u suggest? can u give me link pls? i want use it with js in my asp.net project.

**Comment by ramoona** [comment]
@shkupjane hey, check out https://binlist.net/
