### ISSUE TITLE
Rewrite on es modules with compile into commonjs

### ISSUE THREAD

**Issue by romanlex** [ramoona/banks-db#177]
May be rewrite lib to es modules?
We can compile es modules to commonjs with rollup for example

**Comment by ai** [comment]
For what reason?

**Comment by romanlex** [comment]
use this base in the browser

**Comment by romanlex** [comment]
Example I want use only RU banks or RU and BY

**Comment by ai** [comment]
You do not need ES Modules for partial import. Just do:

```js
var ruBanks = require('./banks/ru')

module.exports = function findBank(cardNumber) {
  cardNumber = cardNumber || '';
  var card = cardNumber.toString().replace(/[^\d]/g, '');
  var first5 = card.substr(0, 5);
  var first6 = card.substr(0, 6);
  var bank = prefixes[first6] || prefixes[first5];
  var result = {
    type: type(card)
  };

  if (bank) {
    for (var el in bank) {
      result[el] = bank[el];
    }
  }

  return result;
};
```

@ramoona maybe we should move `findBank` function to separated file and add instructions to docs about partial import?

**Comment by ramoona** [comment]
@ai as I remember the initial idea was that you never know what card will be used so there's no point to select country :) but ok separating `findBank` sounds good, I'll do that in a few days

**Comment by ramoona** [comment]
v0.15.0 with feature to pick specific banks arrived 💫[details on API](https://github.com/ramoona/banks-db#if-you-need-only-banks-for-specific-countries)
