### ISSUE TITLE
Promote other billing best practices

### ISSUE THREAD

**Issue by ai** [Ramoona/banks-db#21]
I think this repo shoud have “See Also” or “Other Best Practices” section with links:

* [fast-luhn](https://github.com/bendrucker/fast-luhn) to check bank card number for mistakes
* [Halter font](http://www.dafont.com/halter.font) to simulate bank card font
* [convert-layout](https://github.com/ai/convert-layout) to force English keyboard in holder name field

**Comment by Ramoona** [comment]
Thanks for suggestion, done in a4369bcf37baceb9d63ff6a6ed924c43cfa528ed
