### ISSUE TITLE
Missing entry for Google Wallet

### ISSUE THREAD

**Issue by haywardt** [ramoona/banks-db#46]
524825 is prefix for google wallet debit card

**Comment by ai** [comment]
I think we can use Google brand color for it. [brand-colors](https://github.com/reimertz/brand-colors/blob/master/data/brandColors.js) tells that it is `#4285f4`.

**Comment by haywardt** [comment]
The card color is white, or close to it. Maybe #eeeeee.

**Comment by ramoona** [comment]
@haywardt brand color is not a card color, it should be an emitent bank color, so I guess @ai proposal was right. thank you for taking part!

**Comment by haywardt** [comment]
Here are more from the US:
474472 - Bank of America
456527 - BBVA Compass Clearspend
372741 - American Express Serve

Tim Hayward
haywardt@gmail.com
713 364 8855

**Comment by ramoona** [comment]
@haywardt thank you! will add it in project soon

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)
