### ISSUE TITLE
Add more popular USA banks

### ISSUE THREAD

**Issue by ai** [ramoona/banks-db#47]
Seems like we need to add more popular USA banks by our self. Only in this case users will trust in us and contribute.

Reddit users expect that we have AmEx, Chase, BofA, and Capital One banks.

We need to find these BINs somehow.

**Comment by lewiseason** [comment]
Plenty of websites listing BINs - they won't always have every single one, but usually a pretty good chunk. I think the aim behind this project is to provide a more open API as most of the BIN lookup APIs cost lots of money.

Not sure what the rules are on various BIN websites for scraping them and generating JSON from the results...

**Comment by iSeiryu** [comment]
http://www.stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html

**Comment by DCRussian** [comment]
@iSeiryu that's a pretty good list as a general guideline, but a lot of them are outdated now and have been re-used by different banks than the listed once (for example, some Wells Fargo numbers are used by Citibank now).
I would be cautious about taking that list as a gold source.

**Comment by iSeiryu** [comment]
Got some info from my coworkers.

Wells Fargo:
434258
446542
Chase:
414720

**Comment by DanGe42** [comment]
Here are a few that I got as well

Chase (Visa):
414720 (confirms above)
441103

Citi (Mastercard):
542418
540385

Amex:
371587

Wells (Visa):
446540

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)
