### ISSUE TITLE
Natwest UK missing

### ISSUE THREAD

**Issue by charj-it** [ramoona/banks-db#51]
The following is a UK natwest card

4751 30
4751 28

**Comment by ramoona** [comment]
@charj-it thank you! will add soon

**Comment by nic-d** [comment]
4751 27 Is also a Natwest UK card

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)

**Comment by charj-it** [comment]
Nice work!

**Comment by ramoona** [comment]
@charj-it thanks to you :)
