### ISSUE TITLE
Add ING Direct (France) Gold Mastercard

### ISSUE THREAD

**Issue by MathRobin** [ramoona/banks-db#57]
// banks/fr/ingdirect.json
      {
        "name": "ING Direct",
        "prefixes": [
          513625
        ],
        "country": "fr",
        "localTitle": "ING Direct",
        "engTitle": "ING Direct",
        "url": "http://www.ingdirect.fr/",
        "color": "#FF6200"
      }

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)

**Comment by MathRobin** [comment]
Thanks !

**Comment by ramoona** [comment]
@MathRobin thanks to you! ;)
