### ISSUE TITLE
Add LCL (France) Visa

### ISSUE THREAD

**Issue by MathRobin** [ramoona/banks-db#58]
// banks/fr/lcl.json
      {
        "name": "LCL",
        "prefixes": [
          497203
        ],
        "country": "fr",
        "localTitle": "LCL",
        "engTitle": "LCL",
        "url": "https://particuliers.secure.lcl.fr/",
        "color": "#263F92"
      }

**Comment by ramoona** [comment]
@MathRobin thank you! will add it soon :)

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)

**Comment by MathRobin** [comment]
Thanks !
