### ISSUE TITLE
Add Caisse d'Epargne (French) Visa

### ISSUE THREAD

**Issue by raf-a** [ramoona/banks-db#60]
// banks/fr/caisseepargne.json
  {
    "name": "caisseepargne",
    "prefixes": [
      497874
    ],
    "country": "fr",
    "localTitle": "Caisse d'Épargne",
    "engTitle": "Caisse d'Épargne",
    "url": "https://www.caisse-epargne.fr/",
    "color": "#E2001A"
  }

**Comment by ramoona** [comment]
check out [0.9.0 release](https://github.com/ramoona/banks-db/releases/tag/0.9.0) :)
