### ISSUE TITLE
Some of Sberbank prefixes are ambiguous

### ISSUE THREAD

**Issue by vladdenisov** [ramoona/banks-db#76]
According to http://bins.pro/search?action=searchbins&bins=54690&bank=&country= bin `54690`is ambiguous (546900 is HOIUPANK bank). I found all sberbank bins by this search request http://bins.pro/search?action=searchbins&bins=&bank=SBERBANK&country=RU - except 5 first bins all others are sberbank. And from here we can find all 5 and 6-digit bins for sberbank. I'm ready to make pull request which will fix present ambiguous bins and add all known from this database.

**Comment by ai** [comment]
Can you send a PR with HOIUPANK bank and fix in Sberbank’s BINs?

**Comment by kotchuprik** [comment]
And 546945 isn't worked here https://ramoona.github.io/banks-db-demo/
But db contains this BIN :)

**Comment by ramoona** [comment]
@kotchuprik it isn't work because demo uses BanksDB v0.10.1 and this BIN came with v0.10.2 :) 2d8a4fce04b9d24e80ebf6142865dfe6aebea4e3

**Comment by kotchuprik** [comment]
ah, thank you for the answer!
