### ISSUE TITLE
Add demo page with form when include banks-db

### ISSUE THREAD

**Issue by tit** [ramoona/banks-db#8]

**Comment by altmind** [comment]
@ai @Ramoona are you interested in creating demo for banks-db? i may create sample page to test, but without those new trendy technologies(no postcss, no react, no bundling and no angular2)

**Comment by Ramoona** [comment]
@altmind thanks for proposal, demo is nearly done :), I just want to make postcss plugin for it, before releasing. I would appreciate help with this issue https://github.com/Ramoona/banks-db/issues/15

**Comment by ramoona** [comment]
[here](https://github.com/ramoona/banks-db-demo) we go :)
