### ISSUE TITLE
JSON attribute naming convention?

### ISSUE THREAD

**Issue by amio** [ramoona/banks-db#80]
1. Since the "prefixes" actually are ["BIN" or "IIN"](https://en.wikipedia.org/wiki/Bank_card_number), shall we rename `prefixes` to `bin` or `iin`?
1. Some bank logo has two main color, such as [this](https://cloud.githubusercontent.com/assets/215282/14449070/e44d8d0c-00a1-11e6-94dd-0469b4304c1e.gif) or 
[this](https://cloud.githubusercontent.com/assets/215282/14449111/49ff3484-00a2-11e6-81cc-89615239045f.png), how about set two attribute for this? `brandColorPrimary` and `brandColorSecondary`?

**Comment by ai** [comment]
I think “BIN” and “IIN” are internal terms and library users should be able to don’t know them.

Also if ban have 10 BINS like `xxxxx[0-9]` we can write `xxxxx` prefix, but it will not be a BIN anymore.

**Comment by ai** [comment]
Main purpose of brand color is to use it in billing form background. So, at least for library origin purpose, we don‘t need a second color. But of course we are open for use cases :).

**Comment by ramoona** [comment]
@amio I agree with @ai that prefixes != BIN (or IIN), so we shouldn't rename it. As for colors, I think it may be useful to add something like "colorSecondary", but  the main color should stay just "color" ( there's no need to change API :)

**Comment by amio** [comment]
> Also if ban have 10 BINS like xxxxx[0-9] we can write xxxxx prefix, but it will not be a BIN anymore.

Agree with you. Actually I was thinking about shrink some [big](banks/us/americanexpress.json) [files](banks/us/bankofamerica.json) with this idea too.

**Comment by amio** [comment]
@ramoona Sure, a `colorSecondary` without changing api is good too. :D
