### ISSUE TITLE
Copy all BINs from Wikipedia

### ISSUE THREAD

**Issue by ai** [Ramoona/banks-db#9]
Maxim Melnikov found a good list of BINs: http://www.stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html

We need to find a colors and copy this data to DB.

**Comment by altmind** [comment]
If somebody need a quite complete list of Bins with convenient search, you can use bins.pro: http://bins.pro/search?action=searchbins&bins=&bank=&country=RU

**Comment by ai** [comment]
@altmind awesome, links! thanks
