### ISSUE TITLE
Simple bank missing

### ISSUE THREAD

**Issue by tristanseifert** [ramoona/banks-db#95]
[Simple](https://simple.com) cards start with the following six digits:

4811 71

**Comment by tristanseifert** [comment]
Additionally, my [Ally](https://ally.com) MasterCard, starting with the six digits 5575 52, is not recognized.

**Comment by sokos** [comment]
Не распознал карты
**Сбера**
5469 69

**БинБанка**
514093

**Виртуальная от Яндекса**
5106 21
